### ISSUE TITLE
problem with login  deezloader version 3.1.0

### ISSUE THREAD

**Issue by showbert7** [Deezloader/DeezLoader-Reborn#1]
hi @ExtendLord 
i have problem with login 
windows 8.1 64
ram 8 
gpu 9600gso 
hdd 1tb
cpu cor 2 dou 2.8 gigahertz intel 4 core 
 i found this link to resolve my issue but i dont understand.
https://www.w3schools.com/tags/tag_doctype.asp
and error is botton link
https://ibb.co/dmWKkS

**Comment by FleuryK** [comment]
Hello.
I had exactly the same problem.
I clicked "Cancel" and managed to log in without any problem.
The project was on GitLab before it was removed (?) (error 404). That's why there is this <!DOCTYPE html> in the update dialog.
Download the latest version (3.1.0) available here on this GitHub.
Sorry I'm French and my English is not good.

**Comment by RR07** [comment]
Yes. The latest version doesnt work.

**Comment by Deezloader** [comment]
@FleuryK update to the latest version. @RR07 will upload fix soon.

**Comment by FleuryK** [comment]
@Deezloader I have the latest version (3.1.0) and no problem.

**Comment by aswertyn** [comment]
I can't login in android via termux
